### PR TITLE
allow mysql to use customized database

### LINKED ISSUE #33: [mysql] allow to use a customized database instead of default one
hi,

thanks for creating such great tool. It is really saved lots of time to do integration test.
However, we found that you use default "mysql" database (it also called mysql) as your default database.
https://github.com/ory-am/dockertest/blob/master/mysql.go#L35
```
url := fmt.Sprintf("%s:%s@tcp(%s:%d)/mysql", MySQLUsername, MySQLPassword, ip, port)
```
As you may knew, mysql stored user's information and privileges into that database as well. 
That would be an issue if we share the same table names.
I think it is better to let caller decide which one of databases should be used.
And, when mysql container is up, we can create the database if it is not default one.

Let me know your concerns.
If you accept PR, I can send one.

### PR DESCRIPTION
**Pull request by hsinhoyeh**
fixed #33

### CODE REVIEW

**Comment by arekkas** [comment]
Thanks for the PR! Unfortunately there are a few issues:

- [`time.Sleep(10 * time.Second) // take a short break to let mysql get ready`](https://github.com/ory-am/dockertest/pull/34/files#diff-fa6657a0cae6e01d3f083eed96998178R25) causes all tests to significantly take longer.
- [Setting the database name global](https://github.com/ory-am/dockertest/pull/34/files#diff-19b0646d0a3bb4d0dacef28fbf0609b6R74) could be potentially an issue if tests run in parallel. While it is uncommon to use different database versions or images in an application, it is common to use different database names throughout an application. Therefore I don't think that this should be global

How about writing a helper:

```go
func CreateMySQLDatabase(databaseName, connectURL string) (url string, err error)
```

This could be then used like:

```go
    // var db *sql.DB
    c, err := dockertest.ConnectToMySQL(15, time.Millisecond*500, func(url string) bool {
        var err error
        newUrl, err := dockertest.CreateMySQLDatabase("some_database", url)
        if ; err != nil {
            return false
        }

        db, err = sql.Dial(newUrl)
        if err != nil {
             return false
        }

        return db.Ping() == nil
    })
```

**Comment by hsinhoyeh** [comment]
@arekkas, thanks for the comments, your approach sounds good. will update this PR afterwards.

**Comment by hsinhoyeh** [comment]
@arekkas after doing some test, postgres uses username as default database where no tables are predefined.
you can see the message below. Let me know if we need that feature as well.
```
postgres=# \connect postgres;
You are now connected to database "postgres" as user "postgres".
postgres=# \list
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)

postgres=# \dt
No relations found.
```

**Comment by arekkas** [comment]
@hsinhoyeh the default database is `postgres` and the default user is `postgres` as well. The thing is, the `postgres` database is also the maintenance database where user info and so on is stored. I think having a helper for postgres would be cool as well.

**Comment by arekkas** [comment]
PR looks very good! Could you maybe add a little note (or example) to the README as well? :) You can also link to the test case

**Comment by hsinhoyeh** [comment]
@arekkas found it
```
postgres=# select * from pg_user;
 usename  | usesysid | usecreatedb | usesuper | userepl | usebypassrls |  passwd  | valuntil | useconfig
----------+----------+-------------+----------+---------+--------------+----------+----------+-----------
 postgres |       10 | t           | t        | t       | t            | ******** |          |
(1 row)

```
will update both of them later.

**Comment by hsinhoyeh** [comment]
@arekkas I have updated both postgre and readme, see if you like it.

**Comment by arekkas** [comment]
You rock, thanks!

**Pull request merged**
