### PR TITLE
core: add etcd

### PR DESCRIPTION
**Pull request by alanchchen**
# Summary

- Add `etcd` support

### CODE REVIEW

**Comment by arekkas** [comment]
Thank you for you contribution, could you please add tests?

**Comment by alanchchen** [comment]
I'll add it, thanks for your reminder :)

**Comment by alanchchen** [comment]
@arekkas  
Do I need to commit `glide.lock` and `glide.yaml`?
I didn't see these two files in other PRs. How can they pass the test?

**Comment by arekkas** [comment]
`glide up` should do it

**Comment by arekkas** [comment]
so it's compiling now, but it looks like it can't connect to etcd. Any ideas?

**Comment by alanchchen** [comment]
Still figuring out. The etcd test case passed in my computer but other test cases are failed.
Really weird.

**Comment by arekkas** [comment]
Hm, maybe some weird timout setting?

Gesendet mit meinem HTC

----- Reply message -----
Von: "Alan Chen" <notifications@github.com>
An: "ory-am/dockertest" <dockertest@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Mention" <mention@noreply.github.com>
Betreff: [ory-am/dockertest] core: add etcd (#63)
Datum: Sa., Sep. 3, 2016 14:37

Still figuring out. The etcd test case passed in my computer but other test cases are failed.
Really weird.

**Comment by alanchchen** [comment]
@arekkas. I have some questions.   

1. Does it make sense that each test sets `BindDockerToLocalhost` by itself ?

  E.g.,
  ```
  func TestConnectToConsul(t *testing.T) {
  	BindDockerToLocalhost = "true"
          ...
  }
  ```

2. In `vars.go`, `BindDockerToLocalhost` is configured as below  

  ```
  BindDockerToLocalhost = env.Getenv("DOCKERTEST_BIND_LOCALHOST", env.Getenv("DOCKER_BIND_LOCALHOST", "1"))
  ```
  I think the `BindDockerToLocalhost` is always "1" if I don't set it manually, right?



Thanks

**Comment by arekkas** [comment]
> Does it make sense that each test case sets BindDockerToLocalhost by itself ?

Not really, because BindDockerToLocalhost is only useful when you are running the old boot2docker. Why do you want to force it?

> I think the BindDockerToLocalhost will never be "" if I don't set it manually, right?

Yes, this is a bit weird and was done to keep backwards compatibility and also ensure that dockertest works fine with the new docker native clients

**Comment by alanchchen** [comment]
> Not really, because BindDockerToLocalhost is only useful when you are running the old boot2docker. Why do you want to force it?

>Yes, this is a bit weird and was done to keep backwards compatibility and also ensure that dockertest works fine with the new docker native clients

I see. I'm a bit confused about that. Thank you lol.

---

I tried to fix the test failure on my machine. I found the root cause is `BindDockerToLocalhost`.
I'm using OSX so the docker containers run through docker machine.
So if I do not set `BindDockerToLocalhost` to `""` manually, the test cases are always failed.  

Then I change this line
```
BindDockerToLocalhost = env.Getenv("DOCKERTEST_BIND_LOCALHOST", env.Getenv("DOCKER_BIND_LOCALHOST", "1"))
```
to
```
BindDockerToLocalhost = env.Getenv("DOCKERTEST_BIND_LOCALHOST", env.Getenv("DOCKER_BIND_LOCALHOST", ""))
```

Most of the test cases passed. Only two test cases failed.
`TestConnectToCassandra` and `TestConnectToConsul`

Both of them set `BindDockerToLocalhost` manually in their test function.
https://github.com/ory-am/dockertest/blob/master/docker_integration_test.go#L211
https://github.com/ory-am/dockertest/blob/master/docker_integration_test.go#L303

So I asked this question lol

**Comment by arekkas** [comment]
Ok, thanks for reproducing. I will take a look at it myself, but I'm on vacation until next (not this) sunday. :)

**Comment by arekkas** [comment]
Hey, tests pass now! Looks like it was a travis hick up. Sorry for the troubles! :)

**Pull request merged**
