### PR TITLE
3.0.0

### PR DESCRIPTION
**Pull request by arekkas**
TODO:

Pre-API3:
- [ ] Decide whether Specification.Image should be structured, like dockerImage{}
- [ ] Perhaps move template-specifications into their own package? (templates?)
  - Alternatively, flesh out a pure factory-driven model with version-checks.
- [ ] Should SetUp{Postgre,MySQL}Database really be a part of dockertest?

Whenever:
- [ ] Reimplement DockerMachine and LocalDocker into separate Runners, autodetected during package load
  ? Perhaps should affect the API, moving options etc into the implementations rather than the globals?
- [ ] Implement Docker Swarm as a runner

### CODE REVIEW

**Comment by rawler** [comment]
I don't understand the data-races detected in travis. For example, https://github.com/ory-am/dockertest/blob/v3/log.go#L26 and https://github.com/ory-am/dockertest/blob/v3/log.go#L36 are both covered by a mutex, and neither of them seems to perform writes?

**Comment by arekkas** [comment]
`go test -race .` works fine. Maybe it's some bug related to the code coverage tool

**Comment by rawler** [comment]
*ahh* I see the problem. When running with race-detector, you need to either -covermode=atomic, or just omit it and it will default to atomic.

**Comment by arekkas** [comment]
sorry @rawler i didn't have a lot of time to work on this but this PR isn't forgotten :)

**Comment by arekkas** [comment]
I am closing this as this is now #65

**Comment by arekkas** [comment]
pr changed, it's now #66

**Pull request closed without merging**
