### PR TITLE
added image name tag support

### PR DESCRIPTION
**Pull request by bjorn-tf**
I need support of images with tags, like 'postgres:9.4.6', so i added some basic tags parsing of `docker images` output.

### CODE REVIEW

**Comment by arekkas** [comment]
Please add a test for this :)

**Comment by bjorn-tf** [comment]
@arekkas Do you mean unit or integration test?

**Comment by arekkas** [comment]
Why not both? :)

**Comment by bjorn-tf** [comment]
Okay. I get it.

**Comment by bjorn-tf** [comment]
@arekkas Can you please check my updates? I'm not sure that it's good idea to rename dockertest_test package, maybe we should split tests into two files: dockertest_test(package dockertest, for unit tests) and dockertest_integration_test(package docker_integration_test).

**Comment by arekkas** [comment]
Hey sorry for not responding, I overlooked your updates.

The idea of package `docker_test` is, that it already is an integration test, because you don't have access to private methods. If you need access to private stuff, rename the current `docker_test.go` to `docker_integration_test.go` (`package docker_test`) and create a new file `docker_test.go` with (`package docker`).

If you need any further guidance feel free to ping me any time. Sorry again for the delay.

**Comment by bjorn-tf** [comment]
Thats exactly what i mean. The last question - if we want to make integration test for `haveImage()` we should make it public, is it ok?

**Comment by arekkas** [comment]
Oh I see, maybe `HaveImage` is a nice addition to the toolbox and could be useful for people. Let's make it public :)

**Comment by arekkas** [comment]
Cool, looks good to me. Going to check it out locally and merge it afterwards

**Comment by arekkas** [comment]
Thanks!

**Pull request merged**
